//! Route coverage checks against the bundled Redis Enterprise REST API inventory.
//!
//! Compares normalized path templates extracted from the typed handler
//! implementation in `src/` against the `docs/api-inventory.csv` ground
//! truth produced by `scripts/export_api_inventory.py`. Any drift in
//! either direction must be tracked explicitly in an allowlist file so
//! coverage gaps stay visible in review.
//!
//! Mirrors the `openapi_route_coverage.rs` machinery used by
//! `redis-cloud-rs`, adapted to a docs-derived inventory because the
//! Enterprise REST API does not publish an OpenAPI spec we can vendor.
//!
//! See #66 for the umbrella tracking issue.

use regex::Regex;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

const INVENTORY_CSV: &str = include_str!("../docs/api-inventory.csv");
const UNSUPPORTED_ROUTES: &str = include_str!("fixtures/enterprise_unsupported_routes.txt");
const NON_SPEC_ROUTES: &str = include_str!("fixtures/enterprise_non_spec_routes.txt");

const SUPPORTED_VERBS: &[&str] = &["GET", "POST", "PUT", "PATCH", "DELETE"];

/// Normalize a route path: drop query string, replace `{param}` and
/// `<param>` placeholders with `{}`, strip trailing slash. The inventory
/// CSV uses both placeholder styles (the `<>` form appears for
/// auto-generated rows in `api-inventory.csv`), so both have to collapse
/// to the same canonical form to match handler paths.
fn normalize_path(path: &str) -> String {
    let path = path.split('?').next().unwrap_or(path);
    let curly = Regex::new(r"\{[^}]+\}").expect("valid `{}` placeholder regex");
    let angle = Regex::new(r"<[^>]+>").expect("valid `<>` placeholder regex");
    let normalized = curly.replace_all(path, "{}");
    let normalized = angle.replace_all(&normalized, "{}");
    let trimmed = normalized.trim_end_matches('/');
    if trimmed.is_empty() {
        "/".to_string()
    } else {
        trimmed.to_string()
    }
}

/// Parse `docs/api-inventory.csv` into the set of documented routes.
///
/// The CSV is generated by `scripts/export_api_inventory.py`. Header
/// columns are: `page,title,method,path,description,source,source_type,sdk_module_guess,repo_module_exists,status,notes`.
/// Only the `method` and `path` columns matter here.
fn documented_routes() -> BTreeSet<String> {
    let mut lines = INVENTORY_CSV.lines();
    let header = lines
        .next()
        .expect("inventory CSV should have a header row");
    let columns: Vec<&str> = header.split(',').collect();
    let method_col = columns
        .iter()
        .position(|c| *c == "method")
        .expect("inventory CSV should have a `method` column");
    let path_col = columns
        .iter()
        .position(|c| *c == "path")
        .expect("inventory CSV should have a `path` column");

    let mut routes = BTreeSet::new();
    for (idx, line) in lines.enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let fields: Vec<&str> = line.split(',').collect();
        if fields.len() <= method_col || fields.len() <= path_col {
            panic!(
                "inventory CSV row {} is too short: {line:?}",
                idx + 2 // +2 for 1-based + header
            );
        }
        let method = fields[method_col].trim().to_ascii_uppercase();
        let path = fields[path_col].trim();
        if SUPPORTED_VERBS.contains(&method.as_str()) && path.starts_with('/') {
            routes.insert(format!("{method} {}", normalize_path(path)));
        }
    }
    routes
}

/// Read one of the allowlist files and return the set of normalized
/// `METHOD /path` entries. Blank lines and `#`-prefixed comments are
/// ignored.
fn load_allowlist(contents: &str) -> BTreeSet<String> {
    contents
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToOwned::to_owned)
        .collect()
}

/// Walk `src/` (excluding the testing-only modules) and return every
/// `*.rs` path. The `client.rs`, `lib.rs`, and `macros.rs` files don't
/// host handler routes; skip them to keep extraction noise-free.
fn source_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    for entry in fs::read_dir(dir).expect("source directory should be readable") {
        let entry = entry.expect("dir entry");
        let path = entry.path();

        if path.is_dir() {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if name == "testing" {
                continue;
            }
            files.extend(source_files(&path));
            continue;
        }

        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }
        let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        if matches!(
            name,
            "client.rs" | "lib.rs" | "lib_tests.rs" | "macros.rs" | "local.rs"
        ) {
            // client.rs is the HTTP transport, not a handler.
            // local.rs intentionally uses non-spec localhost paths.
            // lib*.rs / macros.rs host no routes.
            continue;
        }
        files.push(path);
    }
    files
}

/// Strip `//`-prefixed line comments. The handler files contain quoted
/// path strings in comments (e.g. `// POST /v1/foo`) that we must not
/// confuse with real handler calls.
fn strip_line_comments(contents: &str) -> String {
    contents
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Extract handler routes from the crate's source tree by scanning for
/// `self.client.<verb>(...)` and `.client.<verb>(&format!(...))` calls
/// in handler modules.
fn extracted_handler_routes() -> BTreeSet<String> {
    // Match `self.client.<verb>(...)` patterns. The capture groups are
    // documented in-line so the regex stays readable.
    //
    // `verb_str` lists every client method on `RestClient` that takes
    // a path as its first argument. Update both lists below in lockstep
    // if a new transport method is added to `src/client.rs`.
    let verbs: &[(&str, &str)] = &[
        ("get", "GET"),
        ("get_text", "GET"),
        ("get_binary", "GET"),
        ("get_raw", "GET"),
        ("post", "POST"),
        ("post_raw", "POST"),
        ("post_action", "POST"),
        ("post_multipart", "POST"),
        ("post_bootstrap", "POST"),
        ("put", "PUT"),
        ("put_raw", "PUT"),
        ("put_action", "PUT"),
        ("patch_raw", "PATCH"),
        ("delete", "DELETE"),
        ("delete_raw", "DELETE"),
    ];

    let alternation = verbs
        .iter()
        .map(|(verb, _)| regex::escape(verb))
        .collect::<Vec<_>>()
        .join("|");

    let direct = Regex::new(&format!(
        r#"\.(?P<verb>{alternation})\(\s*"(?P<path>/[^"\n]*)""#
    ))
    .expect("valid direct-literal regex");
    let formatted = Regex::new(&format!(
        r#"\.(?P<verb>{alternation})\(\s*&?format!\(\s*"(?P<path>/[^"\n]*)""#
    ))
    .expect("valid format!-literal regex");

    let verb_map: std::collections::HashMap<&str, &str> = verbs.iter().copied().collect();

    // impl_crud! { ... } entries — each handler row maps to a verb +
    // path. The macro is documented in `src/macros.rs`. The patterns
    // below cover every entry shape the macro supports.
    let impl_crud_patterns: &[(Regex, &str)] = &[
        (
            Regex::new(r#"list\s*=>\s*\w+\s*,\s*"(?P<path>/[^"\n]+)"\s*;"#)
                .expect("valid impl_crud list regex"),
            "GET",
        ),
        (
            Regex::new(r#"get\s*\([^)]*\)\s*=>\s*\w+\s*,\s*"(?P<path>/[^"\n]+)"\s*;"#)
                .expect("valid impl_crud get regex"),
            "GET",
        ),
        (
            Regex::new(r#"create\s*\([^)]*\)\s*=>\s*\w+\s*,\s*"(?P<path>/[^"\n]+)"\s*;"#)
                .expect("valid impl_crud create regex"),
            "POST",
        ),
        (
            Regex::new(r#"update\s*\([^,)]*,\s*[^)]*\)\s*=>\s*\w+\s*,\s*"(?P<path>/[^"\n]+)"\s*;"#)
                .expect("valid impl_crud update regex"),
            "PUT",
        ),
        (
            Regex::new(r#"delete\s*\([^)]*\)\s*,\s*"(?P<path>/[^"\n]+)"\s*;"#)
                .expect("valid impl_crud delete regex"),
            "DELETE",
        ),
    ];

    let mut routes = BTreeSet::new();
    let src_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("src");

    for file in source_files(&src_dir) {
        let raw = fs::read_to_string(&file).expect("source file readable");
        let contents = strip_line_comments(&raw);

        for caps in direct.captures_iter(&contents) {
            let verb = verb_map[&caps["verb"]];
            let path = &caps["path"];
            routes.insert(format!("{verb} {}", normalize_path(path)));
        }
        for caps in formatted.captures_iter(&contents) {
            let verb = verb_map[&caps["verb"]];
            let path = &caps["path"];
            routes.insert(format!("{verb} {}", normalize_path(path)));
        }

        // `source_files` already excludes macros.rs so the test handler
        // inside the cfg(test) module never adds /v1/test/* routes.
        for (pattern, verb) in impl_crud_patterns {
            for caps in pattern.captures_iter(&contents) {
                let path = &caps["path"];
                routes.insert(format!("{verb} {}", normalize_path(path)));
            }
        }
    }
    routes
}

fn diff(set: &BTreeSet<String>, expected: &BTreeSet<String>) -> Vec<String> {
    set.difference(expected).cloned().collect()
}

#[test]
fn test_documented_routes_have_handler_coverage() {
    let documented = documented_routes();
    let extracted = extracted_handler_routes();
    let allowlist = load_allowlist(UNSUPPORTED_ROUTES);

    let uncovered: BTreeSet<_> = documented.difference(&extracted).cloned().collect();
    let unexpected = diff(&uncovered, &allowlist);
    assert!(
        unexpected.is_empty(),
        "Found documented routes with no handler implementation and no entry in \
         tests/fixtures/enterprise_unsupported_routes.txt. Either implement the \
         handler or add the route to the allowlist (with a comment explaining why):\n\n{}",
        unexpected.join("\n")
    );

    let stale: Vec<_> = allowlist.difference(&uncovered).cloned().collect();
    assert!(
        stale.is_empty(),
        "Found stale allowlist entries in enterprise_unsupported_routes.txt that \
         are now covered by a handler. Remove them from the allowlist:\n\n{}",
        stale.join("\n")
    );
}

#[test]
fn test_non_spec_handler_routes_are_explicitly_allowlisted() {
    let documented = documented_routes();
    let extracted = extracted_handler_routes();
    let allowlist = load_allowlist(NON_SPEC_ROUTES);

    let non_spec: BTreeSet<_> = extracted.difference(&documented).cloned().collect();
    let unexpected = diff(&non_spec, &allowlist);
    assert!(
        unexpected.is_empty(),
        "Found handler routes that are not in the documented inventory and not in \
         tests/fixtures/enterprise_non_spec_routes.txt. Either remove the handler, \
         confirm the route is internal/legacy and add it to the allowlist with a \
         note, or update docs/api-inventory.csv (and rerun \
         `scripts/export_api_inventory.py`):\n\n{}",
        unexpected.join("\n")
    );

    let stale: Vec<_> = allowlist.difference(&non_spec).cloned().collect();
    assert!(
        stale.is_empty(),
        "Found stale allowlist entries in enterprise_non_spec_routes.txt that \
         the handler no longer calls. Remove them from the allowlist:\n\n{}",
        stale.join("\n")
    );
}
